Repository GatorEducator/gatorgrader, pull requests merged in 2019-03, with the labels that each got.

#121 Add OSX and Python version testing on Travis CI
  .pylintrc
  .travis.yml
  Pipfile
  Pipfile.lock
  scripts/cover.sh
  scripts/lint.sh
  scripts/test.sh
Labels: automation, feature, tests

#120 Documentation/addkeyfeatures
  README.md
Labels: documentation

#114 Add link to the PyGotham presentation
  README.md
Labels: documentation

#127 Update README to reflect new sample repos
  README.md
Labels: documentation

#132 Feature/multi line docstrings
  .pylintrc
  gator/comments.py
  gator/invoke.py
  tests/test_comments.py
  tests/test_invoke.py
  tests/test_orchestrate.py
  tests/test_run.py
Labels: feature
