Repository GatorEducator/gatorgrader, pull requests merged in 2019-05, with the labels that each got.

#160 Automated PR releases
  .travis.yml
Labels: automation

#164 Add Windows Support and AppVeyor CI
  .appveyor.yml
  .travis.yml
  Pipfile
  Pipfile.lock
  README.md
  gator/entities.py
  gator/files.py
  gator/fragments.py
  gator/invoke.py
  gator/markdown.py
  scripts/cover.bat
  scripts/lint.bat
  scripts/test.bat
  tests/test_files.py
  tests/test_invoke.py
  tests/test_run.py
Labels: automation, fix

#165 Add Correct Support for File Name Case Across Operating Systems
  .pylintrc
  .travis.yml
  gator/files.py
  gator/util.py
  tests/test_files.py
Labels: bug, fix, patch
