Repository GatorEducator/gatorgrader, pull requests merged in 2019-02, with the labels that each got.

#108 Creating a LICENSE.md file
  LICENSE.md
Labels: documentation

#109 Add black checking in Travis CI
  .travis.yml
  tests/test_run.py
Labels: linting

#107 Add correct coverage details
  README.md
Labels: documentation, fix

#112 Remove pytest-clarity
  .travis.yml
  Pipfile
  Pipfile.lock
  gator/orchestrate.py
Labels: fix, tests

#113 Issue 81 45
  Pipfile.lock
  tests/test_fragments.py
Labels: documentation, fix, tests

#105 Implement a Markdown AST Parser
  Pipfile
  Pipfile.lock
  gator/fragments.py
  tests/test_fragments.py
Labels: improve
