Repository GatorEducator/gatorgrader, pull requests merged in 2019-04, with the labels that each got.

#134 Issue 88 installation docs
  README.md
Labels: documentation

#130 Feature/markup tag check
  Pipfile
  Pipfile.lock
  README.md
  gator/arguments.py
  gator/fragments.py
  gator/invoke.py
  gator/markdown.py
  gator/orchestrate.py
  tests/test_fragments.py
  tests/test_markdown.py
  tests/test_orchestrate.py
Labels: command-line, feature

#122 Refactor reporting system so that only one report exists
  gator/invoke.py
  gator/orchestrate.py
  gator/report.py
  tests/test_invoke.py
  tests/test_report.py
Labels: fix, improve, refactor, tests

#143 Fix critical word counting bug
  gator/fragments.py
  tests/test_fragments.py
Labels: bug, critical

#149 Fix typo in PR template
  .github/pull_request_template.md
Labels: documentation

#151 added gator grader logo .psd file for editing and .svg file
  .github/gatorgraderlogo.psd
  .github/gatorgraderlogo.svg
Labels: documentation

#157 Add Codacy code quality grading
  .coveragerc
  .pylintrc
  .travis.yml
  Pipfile
  Pipfile.lock
  README.md
  bandit.yml
  pytest.cov
  scripts/cover.sh
  scripts/lint.sh
  setup.cfg
Labels: automation, linting, security, tests

#159 Fix linting issues in markdown issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: fix, linting
