Repository GatorEducator/gatorgrader, pull requests merged in 2022-10, with the labels that each got.

#241 Add metadata for PyPI publishing
  .github/workflows/publish.yml
  README.md
  gator/__init__.py
  gator/checkers.py
  gator/checks/check_ConfirmFileExists.py
  gator/checks/check_CountCommandOutput.py
  gator/checks/check_CountCommits.py
  gator/checks/check_CountFileLines.py
  gator/checks/check_CountFileParagraphs.py
  gator/checks/check_CountFileWords.py
  gator/checks/check_CountMarkdownTags.py
  gator/checks/check_CountMultipleLineComments.py
  gator/checks/check_CountParagraphWords.py
  gator/checks/check_CountSingleLineComments.py
  gator/checks/check_ExecuteCommand.py
  gator/checks/check_ListChecks.py
  gator/checks/check_MatchCommandFragment.py
  gator/checks/check_MatchCommandRegex.py
  gator/checks/check_MatchFileFragment.py
  gator/checks/check_MatchFileRegex.py
  gator/display.py
  gator/exceptions.py
  gator/leave.py
  gator/orchestrate.py
  gator/report.py
  gatorgrader.py
  pyproject.toml
  tests/checks/test_check_ConfirmFileExists.py
  tests/checks/test_check_CountCommandOutput.py
  tests/checks/test_check_CountCommits.py
  tests/checks/test_check_CountFileLines.py
  tests/checks/test_check_CountFileParagraphs.py
  tests/checks/test_check_CountFileWords.py
  tests/checks/test_check_CountMarkdownTags.py
  tests/checks/test_check_CountMultipleLineComments.py
  tests/checks/test_check_CountParagraphWords.py
  tests/checks/test_check_CountSingleLineComments.py
  tests/checks/test_check_ExecuteCommand.py
  tests/checks/test_check_ListChecks.py
  tests/checks/test_check_MatchCommandFragment.py
  tests/checks/test_check_MatchCommandRegex.py
  tests/checks/test_check_MatchFileFragment.py
  tests/checks/test_check_MatchFileRegex.py
  tests/conftest.py
  tests/test_checkers.py
  tests/test_display.py
  tests/test_gator.py
  tests/test_invoke.py
  tests/test_leave.py
  tests/test_orchestrate.py
  tests/test_report.py
Labels: feature, documentation, infrastructure

#244 Update README.md with details/fixes for poetry integration
  README.md
Labels: documentation

#242 Add expected number of fragments to output
  gator/invoke.py
Labels: feature, fix
